{"trial_id": "00", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "filters_1", "default": null, "conditions": [], "min_value": 32, "max_value": 64, "step": 16, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_1", "default": 0.2, "conditions": [], "min_value": 0.2, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "filters_2", "default": null, "conditions": [], "min_value": 64, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_2", "default": 0.2, "conditions": [], "min_value": 0.2, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "filters_3", "default": null, "conditions": [], "min_value": 128, "max_value": 256, "step": 64, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_3", "default": 0.3, "conditions": [], "min_value": 0.3, "max_value": 0.6, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "dense_units", "default": null, "conditions": [], "min_value": 64, "max_value": 256, "step": 64, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_dense", "default": 0.3, "conditions": [], "min_value": 0.3, "max_value": 0.6, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.0001, "conditions": [], "values": [0.0001, 0.0005, 0.001], "ordered": true}}], "values": {"filters_1": 32, "dropout_1": 0.2, "filters_2": 64, "dropout_2": 0.2, "filters_3": 256, "dropout_3": 0.3, "dense_units": 192, "dropout_dense": 0.4, "learning_rate": 0.001}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\juanm\\Desktop\\Workspace\\ia\\AI-CNN-Pneumonia-COVID-Detection\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\juanm\\Desktop\\Workspace\\ia\\AI-CNN-Pneumonia-COVID-Detection\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\juanm\\Desktop\\Workspace\\ia\\AI-CNN-Pneumonia-COVID-Detection\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\juanm\\Desktop\\Workspace\\ia\\AI-CNN-Pneumonia-COVID-Detection\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\juanm\\Desktop\\Workspace\\ia\\AI-CNN-Pneumonia-COVID-Detection\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\juanm\\Desktop\\Workspace\\ia\\AI-CNN-Pneumonia-COVID-Detection\\.venv\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\juanm\\Desktop\\Workspace\\ia\\AI-CNN-Pneumonia-COVID-Detection\\.venv\\Lib\\site-packages\\keras\\src\\backend\\tensorflow\\trainer.py\", line 132, in multi_step_on_iterator\n    one_step_on_data(iterator.get_next())\nSystemError: D:\\a\\1\\s\\Objects\\listobject.c:338: bad argument to internal function\n"}